### ISSUE TITLE
Could not load project 'GeniusReferrals.UWP/GeniusReferrals.UWP.csproj' with unknown item type '{A5A43C5B-DE2A-4C0C-9213-0A381AF9435A}'

### ISSUE THREAD

**Issue by AlperenSarac** [GeniusReferrals/Genius-Referrals-CS#2]
I got the following error when opening the solution file with Xamarin (5.10.3).

Could not load project 'GeniusReferrals.UWP/GeniusReferrals.UWP.csproj' with unknown item type '{A5A43C5B-DE2A-4C0C-9213-0A381AF9435A}'

Can you please look into the issue? Thanks.

**Comment by alainhl** [comment]
Hi @AlperenSarac, 

Thank you for reporting this. We will take a look shortly.
